name = "gleam_hexpm"
version = "1.0.0"
description = "Gleam dynamic decoders for the API of Hex, the package manager for the BEAM ecosystem."

licences = ["Apache-2.0"]
repository = { type = "github", user = "gleam-lang", repo = "hexpm" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]
gleam = ">= 0.33.0"

[dependencies]
gleam_stdlib = "~> 0.34"
birl = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_json = "~> 0.7"
